<a href="https://colab.research.google.com/github/jacktonomondi439-alt/CIR-203-SEPT-DEC-2025/blob/main/transaction_volume.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Let's assume some transaction volume data (in thousands)
# Each row is a branch, each column is a month.
transaction_volumes = np.array([
    [1200, 1350, 1100, 1400, 1550, 1450],  # Branch 1
    [900, 950, 1050, 1100, 1000, 980],    # Branch 2
    [1800, 1950, 2050, 2100, 2000, 1980],  # Branch 3
    [750, 800, 820, 780, 850, 880]        # Branch 4
])

print("2D NumPy Array of Transaction Volumes:")
print(transaction_volumes)

2D NumPy Array of Transaction Volumes:
[[1200 1350 1100 1400 1550 1450]
 [ 900  950 1050 1100 1000  980]
 [1800 1950 2050 2100 2000 1980]
 [ 750  800  820  780  850  880]]


In [ ]:
total_per_branch = np.sum(transaction_volumes, axis=1)

for i, total in enumerate(total_per_branch):
    print(f"Branch {i+1} Total Transactions: {total}")

Branch 1 Total Transactions: 8050
Branch 2 Total Transactions: 5980
Branch 3 Total Transactions: 11880
Branch 4 Total Transactions: 4880


In [ ]:
highest_branch_index = np.argmax(total_per_branch)
# Add 1 to the index because branches are 1-4, while indices are 0-3
print(f"\nThe branch with the highest transaction volume is: Branch {highest_branch_index + 1}")


The branch with the highest transaction volume is: Branch 3


In [ ]:
average_monthly_volume = np.mean(transaction_volumes, axis=0)

for i, avg in enumerate(average_monthly_volume):
    print(f"Month {i+1} Average Volume: {avg:.2f}")

# Overall average across all branches and months
overall_average = np.mean(transaction_volumes)
print(f"\nOverall average monthly transaction volume: {overall_average:.2f}")

Month 1 Average Volume: 1162.50
Month 2 Average Volume: 1262.50
Month 3 Average Volume: 1255.00
Month 4 Average Volume: 1345.00
Month 5 Average Volume: 1350.00
Month 6 Average Volume: 1322.50

Overall average monthly transaction volume: 1282.92


In [ ]:
reshaped_array = transaction_volumes.reshape(3, 8)

print("\nReshaped Array (3x8):")
print(reshaped_array)


Reshaped Array (3x8):
[[1200 1350 1100 1400 1550 1450  900  950]
 [1050 1100 1000  980 1800 1950 2050 2100]
 [2000 1980  750  800  820  780  850  880]]
